# Generated by Django 5.0.7 on 2024-08-30 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('house_name', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('qualification_proof', models.FileField(blank=True, null=True, upload_to='qualification_proofs/')),
                ('application_submitted', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('admin_rejected', models.BooleanField(default=False)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('first_login', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('interests', models.ManyToManyField(blank=True, to='admin_api.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
